# Generated by Django 4.2.3 on 2023-08-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='phone_no',
            field=models.CharField(default=1234567890, max_length=10),
        ),
    ]
